wario-land/WL4Editor

- LevelComponents/Door.cpp
- LevelComponents/Door.h
I think you should use namespace in header file
and I just add the functions for Door class, I will implement these functions tomorrow quickly, but you had better remove all the namespace declaration in cpp file or use them just in the header file. Because I don't think C++ support for namespace connection with the same namespace in different files and we also should use namespace in header file.
I just make an example in door class and implement the code for it.
> add member functions for Door

- LevelComponents/Door.cpp
- LevelComponents/Door.h
- LevelComponents/Level.cpp
- LevelComponents/Level.h
- ROMUtils.cpp
- WL4Constants.h
1. fix some problem in Door class
2. add some TODOs
3. add __LevelHeader sturct
3. implement Level::SetTimeCountdownCounter()
4. some other things
> add more details

- LevelComponents/Level.cpp
- LevelComponents/Level.h
- ROMUtils.cpp
- ROMUtils.h
- main.cpp
i have not implement for every characters but only the number characters and the Latin letters.
> add code for loading levelname

- Dialog/LevelConfigDialog.cpp
- Dialog/LevelConfigDialog.h
- Dialog/LevelConfigDialog.ui
- LevelComponents/EntitySet.cpp
- LevelComponents/EntitySet.h
- LevelComponents/Level.cpp
- LevelComponents/Level.h
- LevelComponents/Room.cpp
- LevelComponents/Room.h
- WL4Constants.h
- WL4EditorWindow.cpp
- WL4EditorWindow.h
also fix a typo "BLend" to "Blend"
> set Validator for dialog QLineedit

- WL4EditorWindow.cpp
- main.cpp
Such as Chinese or Japanese in the path.
> Fix failed open file when there are wide-character in the path

- CHANGELOG
- Dialog/DoorConfigDialog.cpp
- LevelComponents/Room.cpp
- LevelComponents/Room.h
- ROMUtils.cpp
- WL4Constants.h
- WL4EditorWindow.cpp
- WL4EditorWindow.ui
- Disable most menu buttons before ROM is loaded
- Fix changing the destination door in DoorConfigDialog intermittently crashes
- Fix rendering of certain entities in Room.cpp crashes editor
> Bugfixes for beta-3

- CHANGELOG
- Dialog/DoorConfigDialog.cpp
- Dialog/DoorConfigDialog.h
- DockWidget/Tile16DockWidget.cpp
- LevelComponents/Entity.h
- LevelComponents/EntitySet.cpp
- LevelComponents/EntitySet.h
- LevelComponents/Layer.cpp
- LevelComponents/Layer.h
- LevelComponents/Level.cpp
- LevelComponents/Room.cpp
- LevelComponents/Room.h
- LevelComponents/Tile.cpp
- LevelComponents/Tile.h
- LevelComponents/Tileset.cpp
- ROMUtils.cpp
- ROMUtils.h
- WL4Constants.h
- WL4EditorWindow.cpp
- WL4EditorWindow.h
- Fix changing camera limitators then saving causes ROM to not boot
- Fix some spinbox conditions for camera limitators
- Fix loading a second ROM file doesn't work
- Fix several memory leaks
> beta-5 changes

- EditorWindow/MainGraphicsView.cpp
I think it is more convenient if we can copy an already placed tile with a right click.
It allows faster editing.
> Possibility to copy an already placed tile with right click

- CHANGELOG
- LevelComponents/Room.cpp
- LevelComponents/Room.h
- WL4EditorWindow.cpp
- WL4EditorWindow.h
delete out-of-range elements when shrinking Room size.
support using pageUp & pageDown keys to go to different Rooms.
> Add 2 new features

- CHANGELOG
- EditorWindow/MainGraphicsView.cpp
- LevelComponents/Level.cpp
- LevelComponents/Room.cpp
- Operation.cpp
- WL4Application.h
- WL4Editor.pro
- WL4EditorWindow.cpp
- WL4EditorWindow.h
- main.cpp
- Fix an edge case bug: update entity list dock widget everytime if delete Door(s).
- Support deleting everything except camera settings with "Ctrl + Del"
> A bugfix and support clearing CurrentRoom with "Ctrl + Del"

- CHANGELOG
- Operation.cpp
> Fix undo multiple times then placing a tile crashes the editor

- SettingsUtils.cpp
- SettingsUtils.h
- WL4Editor.pro
- WL4EditorWindow.cpp
- WL4EditorWindow.h
- main.cpp
> Add support of WL4Editor.ini

- LevelComponents/Room.cpp
- LevelComponents/Room.h
- WL4EditorWindow.cpp
> Fix the crash problem for adding new rooms

- Dialog/RoomConfigDialog.cpp
- Dialog/RoomConfigDialog.h
- Dialog/RoomConfigDialog.ui
- Dialog/TilesetEditDialog.cpp
- Dialog/TilesetEditDialog.h
- Dialog/TilesetEditDialog.ui
- Dialog/TilesetEditor_Tile8x8MapGraphicView.cpp
- Dialog/TilesetEditor_Tile8x8MapGraphicView.h
- DockWidget/EditModeDockWidget.cpp
- DockWidget/Tile16DockWidget.cpp
- EditorWindow/MainGraphicsView.cpp
- LevelComponents/Tile.cpp
- LevelComponents/Tile.h
- LevelComponents/Tileset.cpp
- LevelComponents/Tileset.h
- ROMUtils.cpp
- WL4Constants.h
- WL4EditorWindow.cpp
- main.cpp
Fix #249 
Fix #252 
Fix #254 
Fix an edge case bug in the main graphicview mouse events, which will crashes the editor when editing layer 0 in undefiend area.
> Several bugfixes and improvement

- Dialog/LevelConfigDialog.cpp
- Dialog/LevelConfigDialog.h
- LevelComponents/Level.cpp
- LevelComponents/Level.h
- WL4EditorWindow.cpp
> Fix camera limitators

- PatchUtils.cpp
> Fix incorrect length calculated during patch deserialization

- DockWidget/CameraControlDockWidget.cpp
- DockWidget/CameraControlDockWidget.h
- LevelComponents/Level.cpp
- LevelComponents/Level.h
- LevelComponents/Room.h
- ROMUtils.cpp
- WL4EditorWindow.cpp
- WL4EditorWindow.h
> There must always be at least 1 camera limitator if that mode is selected

- DockWidget/Tile16DockWidget.cpp
- DockWidget/TileGraphicsView.h
> Fixed #269 

- Dialog/RoomConfigDialog.cpp
- Dialog/RoomConfigDialog.h
- Dialog/RoomConfigDialog.ui
> Support sprite priority elevation in Room Configuration Dialog

- WL4EditorWindow.cpp
> Automatically change to "Follow Wario" when creating new room

- LevelComponents/Level.cpp
> Fix check when determining how many rooms have limitators

- DockWidget/CameraControlDockWidget.ui
- DockWidget/Tile16DockWidget.cpp
- DockWidget/TileGraphicsView.cpp
- DockWidget/TileGraphicsView.h
- EditorWindow/MainGraphicsView.cpp
- WL4EditorWindow.cpp
- WL4EditorWindow.h
> random fixes

- Dialog/CreditEditor_TableView.cpp
- Dialog/CreditEditor_TableView.h
- Dialog/CreditsEditDialog.cpp
- Dialog/CreditsEditDialog.h
- Dialog/CreditsEditDialog.ui
- Dialog/CustomQTableView.cpp
- Dialog/CustomQTableView.h
- Operation.h
- WL4Constants.h
- WL4Editor.pro
- WL4EditorWindow.cpp
- WL4EditorWindow.h
- WL4EditorWindow.ui
I don't know if it can use RATS in some way (anyway nothing is compressed here so I think there is no use)
> Credit Editor can be considered as done I guess

- ROMUtils.cpp
> Fix offset when calculating free space regions

- ROMUtils.cpp
update phantomstyle and fix #303
> update phantomstyle to fix build error for Qt newest verions' internal changes and one other fix in save engine

- Dialog/SpritesEditorDialog.cpp
- Dialog/SpritesEditorDialog.h
- Dialog/SpritesEditorDialog.ui
- LevelComponents/Entity.cpp
- LevelComponents/Entity.h
> Add Oam Designer

- Dialog/RoomConfigDialog.h
- LevelComponents/Layer.h
- WL4EditorWindow.cpp
Fix #315 
now Layer 0 and Layer 2 can have data recovery when undo disable operation on them (layer 0 is a bit different and complicated, but the data recovery still work)
> Room config enhancement and bugfixes

- Dialog/PatchEditDialog.cpp
- Dialog/PatchEditDialog.ui
- PatchUtils.cpp
- Fix #313 
- Add title to patch edit dialog
- Populate patch file path with full path
> Fix incorrectly accepting size for patch chunks

- Dialog/DoorConfigDialog.cpp
- Dialog/DoorConfigDialog.h
> No more info dialog when setting door type to type 1 (portal & door) in Door Config Dialog

- Dialog/RoomConfigDialog.cpp
> fix layer priority setting cannot work correctly caused by some edge cases

- DockWidget/CameraControlDockWidget.cpp
> bugfix on camera box wrong auto-reset when clicking listview in Camera Config Dock Widget

- Dialog/RoomConfigDialog.ui
> add scroll area to Room Config Dialog

- Dialog/PatchManagerDialog.cpp
- PatchUtils.cpp
> fix edit patch

- DockWidget/EditModeDockWidget.cpp
- DockWidget/EditModeDockWidget.h
- DockWidget/EntitySetDockWidget.cpp
- DockWidget/EntitySetDockWidget.h
- EditorWindow/MainGraphicsView.cpp
- EditorWindow/MainGraphicsView.h
- LevelComponents/Room.cpp
- Operation.cpp
- WL4EditorWindow.cpp
auto update entityset dock widget when adding new entity or selecting existing entity on entity editing mode
Close #215
> auto update entityset dock widget

- Dialog/PatchManagerDialog.cpp
now we cannot patch the first 4 bytes of the rom
this solves multiple patches on address 0 cannot be detected too
> fix a wrong logic in patch validate logic

- PatchUtils.cpp
- ROMUtils.cpp
- ROMUtils.h
- main.cpp
> Fix chunks not being invalidated in SaveLevel

- Dialog/RoomConfigDialog.cpp
- FileIOUtils.cpp
- FileIOUtils.h
- LevelComponents/Tile.cpp
- LevelComponents/Tile.h
- LevelComponents/Tileset.cpp
- LevelComponents/Tileset.h
- Operation.cpp
- ROMUtils.cpp
- ROMUtils.h
- WL4EditorWindow.cpp
- WL4EditorWindow.h
- WL4EditorWindow.ui
- main.cpp
Fix #352 
support detecting nintendo intro and reject rom with intro
Support importing Tileset from another rom
> support detecting nintendo intro

- Dialog/CreditsEditDialog.cpp
- Dialog/PatchEditDialog.cpp
- Dialog/PatchManagerDialog.cpp
- Dialog/SpritesEditorDialog.cpp
- FileIOUtils.cpp
- FileIOUtils.h
- LevelComponents/Entity.cpp
- LevelComponents/EntitySet.cpp
- LevelComponents/Layer.cpp
- LevelComponents/Level.cpp
- LevelComponents/Room.cpp
- LevelComponents/Tile.cpp
- LevelComponents/Tile.h
- LevelComponents/Tileset.cpp
- Operation.cpp
- Operation.h
- PatchUtils.cpp
- ROMUtils.cpp
- ROMUtils.h
- ScriptInterface.cpp
- WL4EditorWindow.cpp
- WL4EditorWindow.h
- main.cpp
> Current file meta data impl and problems fix on OperationParams

- Dialog/PatchEditDialog.cpp
- Dialog/PatchEditDialog.h
- Dialog/PatchEditDialog.ui
- Dialog/PatchManagerDialog.cpp
- Dialog/PatchManagerDialog.ui
- Dialog/PatchManagerTableView.cpp
- Dialog/PatchManagerTableView.h
- Dialog/RoomPreviewGraphicsView.h
- PatchUtils.cpp
> Several feature tweaks in Chunk Manager

- .github/workflows/main.yml
- Dialog/DoorConfigDialog.cpp
- Dialog/DoorConfigDialog.ui
- Dialog/SpritesEditorDialog.ui
- Dialog/TilesetEditDialog.cpp
- Dialog/TilesetEditDialog.ui
- DockWidget/CameraControlDockWidget.cpp
- DockWidget/CameraControlDockWidget.ui
- DockWidget/EntitySetDockWidget.cpp
- DockWidget/Tile16DockWidget.cpp
- FileIOUtils.cpp
- LevelComponents/Door.h
- LevelComponents/EntitySet.cpp
- ScriptInterface.cpp
- WL4EditorWindow.cpp
> Dec2hex UI

- LevelComponents/Room.cpp
- LevelComponents/Room.h
Resolve #382 
clean up some useless logic from the entity positional moving logic
> Resolve #382 

- Operation.cpp
> Reset entityset dock widget when applying room config changes

- Dialog/SelectColorDialog.cpp
- Dialog/SelectColorDialog.h
- Dialog/SpritesEditorDialog.cpp
- Dialog/TilesetEditDialog.cpp
- FileIOUtils.cpp
- FileIOUtils.h
> Add window title for Select Color Dialog for all those transparent pixel conversion

- AssortedGraphicUtils.cpp
- AssortedGraphicUtils.h
- CHANGELOG
- Dialog/GraphicManagerDialog.cpp
- Dialog/GraphicManagerDialog.h
- Dialog/TilesetEditDialog.cpp
- LevelComponents/Room.cpp
- LevelComponents/Tileset.cpp
- SettingsUtils.cpp
- SettingsUtils.h
- WL4Constants.h
- WL4EditorWindow.cpp
- WL4EditorWindow.h
Resolve #363 
Fix #394 
Fix #395
> Project settings in json file, and some bugfixes and one hotfix

- Dialog/DoorConfigDialog.cpp
- DockWidget/EditModeDockWidget.cpp
- DockWidget/EditModeDockWidget.h
- DockWidget/EditModeDockWidget.ui
- LevelComponents/Room.cpp
- SettingsUtils.cpp
- SettingsUtils.h
- WL4EditorWindow.cpp
- WL4EditorWindow.h
- WL4EditorWindow.ui
now the color of door and entity boxes can be changed in project json too.
the old "view hidden coin" feature got replaced by "View Extra Hints", support showing terrain and event id hints, while all the id hints can be represented with a customized character which can be config in the project json setting file.
Close #372
> More project json stuff

- SettingsUtils.cpp
- SettingsUtils.h
- WL4EditorWindow.cpp
- WL4EditorWindow.h
- WL4EditorWindow.ui
> Add recent script menu feature

- Dialog/AnimatedTileGroupEditorDialog.cpp
- Dialog/AnimatedTileGroupEditorDialog.h
- Dialog/AnimatedTileGroupEditorDialog.ui
- Dialog/RoomConfigDialog.cpp
- Dialog/SpritesEditorDialog.cpp
- FileIOUtils.cpp
- LevelComponents/AnimatedTile8x8Group.cpp
- LevelComponents/AnimatedTile8x8Group.h
- LevelComponents/Entity.cpp
- LevelComponents/Tileset.cpp
- LevelComponents/Tileset.h
- Operation.cpp
- Operation.h
- ROMUtils.cpp
- ROMUtils.h
- ScriptInterface.cpp
- ScriptInterface.h
- WL4Constants.h
- WL4Editor.pro
- WL4EditorWindow.cpp
- WL4EditorWindow.h
- WL4EditorWindow.ui
> Add animated tiles editor and one small UI logic fix

- LevelComponents/Tileset.cpp
- PatchUtils.cpp
- PatchUtils.h
> fix a incorrect logic in Tile16 reset for x and y flip

- Dialog/RoomConfigDialog.h
- LevelComponents/Layer.cpp
- LevelComponents/Layer.h
- LevelComponents/Room.cpp
- LevelComponents/Room.h
- ROMUtils.cpp
- WL4EditorWindow.cpp
let the alpha blend and layer priority all maint by RenderEffect in the RoomHeader.
Fix random rom corruption after adding new Room and save changes.
> small changes and bugfixes on layer and Room stuff

- Dialog/CreditEditor_TableView.cpp
- Dialog/CreditEditor_TableView.h
- Dialog/CreditsEditDialog.cpp
- Dialog/CreditsEditDialog.h
- Dialog/DoorConfigDialog.cpp
- Dialog/RoomConfigDialog.h
- DockWidget/CameraControlDockWidget.cpp
- EditorWindow/MainGraphicsView.cpp
- LevelComponents/Room.cpp
- LevelComponents/Room.h
- Operation.cpp
- README.md
- ROMUtils.cpp
- ScriptInterface.cpp
- WL4EditorWindow.cpp
- main.cpp
- fix the release tab in the readme file does not have a valid link.
- add the WL4Editor icon provider as one contributor
- Add unused copyright scene in Credit Editor
- Support another one-tile height orange English letter input in Credit Editor
- Support lowercase letter input for 2-tile height case in the Credit Editor
- Fix Credit Editor cannot render the English point
- remove some useless variables from Room class
- Fix rendering the Room twice when using buttons to go to neighbor Rooms
> random things update, small features and bugfixes start from 20230313

- Dialog/RoomConfigDialog.cpp
- Dialog/RoomConfigDialog.h
- ScriptInterface.cpp
- WL4EditorWindow.cpp
Fix ScriptInterface::SetRoomSize(...) cannot work
Fix "Clear all" and Room size change cannot modify Doors in the current Room
put changes made by ScriptInterface::SetRoomSize(...) into the operation list
> 2 new hotfixes 20230519
